
export default async function Head({params}) {

    const {slug} = params

    const res = await fetch('https://thebasics.sachinsblog.in/api/classes')
    const classes = await res.json()
    const cohort = classes.find(cohort => cohort.slug === slug)
    

    return (
      <>
        <title>{cohort.title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </>
    )
  }
  